### ISSUE TITLE
Java Instant serialisation exception

### ISSUE THREAD

**Issue by austek** [spring-projects/spring-pulsar#427] opened 2023-07-28 09:42 UTC
Using `org.springframework.pulsar:spring-pulsar-reactive-spring-boot-starter:0.2.0`

When the class for a topic contains an Instant attribute I get an error
```
org.apache.pulsar.client.api.SchemaSerializationException: [org.apache.pulsar.shade.com](http://org.apache.pulsar.shade.com/).fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type 'java.time.Instant' not supported by default: add Module "org.apache.pulsar.shade.com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
```

However, when using `org.springframework.pulsar:spring-pulsar-reactive-spring-boot-starter:0.2.1-SNAPSHOT` I don't get any errors but when a message is sent by the producer, the message is actually not sent to the topic, at least it is not on the topic and there are no logs either

Here is the project I'm using https://github.com/austek/dataflow-pipeline

Run application
`./gradlew bootRun`

Sent a request
`echo '{"name": "Sensor1", "value": '20', "time":"2023-07-28T09:39:32.217731Z"}'  | curl -X POST -T - -H "Content-Type: application/x-ndjson" localhost:8081/sensors`

**Comment by onobc** [comment] 2023-07-29 04:26
Ok, I see what is going on. sending w/ the Flux looks like its "working" or at least does not have the Jackson error - but it does. If you look at the returned `MessageSendResult` you will see there is an error on it (the serialization error). 

* When sending as a single message the error is surfaced. 
* When sending many and the MessageSendResult does not fail, but has an exception attached to it. 

I can't remember if this is by design or not. Regardless, if you modify your controller as follows:

```java
@PostMapping("/sensors")
Mono<Void> ingest(@RequestBody Flux<SensorEvent> sensorEventFlux) {
    return pulsarTemplate.send(
            SENSOR_INGEST_TOPIC_NAME,
            sensorEventFlux
                    .doOnNext(sensorEvent -> logger.info("About to send sensors entry {}", sensorEvent))
                    .map(sensorEvent ->
                            MessageSpec.builder(sensorEvent).key(sensorEvent.name()).build()
                    ),
            Schema.JSON(SensorEvent.class)
    )
			.doOnError((ex) -> System.out.println("ERROR: " + ex))
			.doOnNext((sendResult) -> System.out.println("RESULT: " + sendResult.getException()))
			.then();
}
```
to do the following, you can see the underlying exception:

> 2023-07-28T23:06:05.763-05:00 TRACE 23650 --- [r-client-io-1-1] o.s.p.r.c.ReactivePulsarTemplate         : Sent messages to 'sensors_ingest' topic
RESULT: org.apache.pulsar.client.api.SchemaSerializationException: org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "org.apache.pulsar.shade.com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.collibra.events.model.SensorEvent["time"])
2023-07-28T23:07:25.691-05:00  INFO 23650 --- [oundedElastic-1] o.a.p.r.c.i.a.ProducerCacheEntry         : Closed producer standalone-0-6 for topic sensors_ingest



The Jackson modules have been added in Pulsar Client 3.0.0 (https://github.com/apache/pulsar/pull/19161).

To take advantage of this in your spring-pulsar:0.2.1-SNAPSHOT app you must add the following to sensor-service/build.gradle.kts:
```
implementation("org.apache.pulsar:pulsar-client-reactive-adapter:0.3.0")
implementation("org.apache.pulsar:pulsar-client-reactive-producer-cache-caffeine:0.3.0")
implementation("org.apache.pulsar:pulsar-client-all:3.0.0")

```

Then you can see the messages are actually sent and received.


> 2023-07-29T03:27:15,477+0000 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/sensors_ingest][bono-sensors-3] Subscribed to topic on localhost/127.0.0.1:6650 -- consumer: 0
----- got message -----
key:[Sensor2], properties:[], content:{"name":"Sensor2","value":20.0,"time":1690537172.217731000}


The team will do the following:
1. Figure out if the error wrapped in the send result is expected or not.
2. Possibly release a `0.2.1` proper that uses reactive client `0.3.0` and pulsar client `3.0.0`.

**Comment by cbornet** [comment] 2023-08-02 20:47
This behavior is configurable : https://github.com/apache/pulsar-client-reactive/blob/7bee05d794e80e7784a707a55a6ecebad4dd4e01/pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageSenderBuilder.java#L85

**Comment by onobc** [comment] 2023-08-03 02:52
Thanks for the clarification @cbornet - I vaguely remember chatting about this at some point in the past. :)

**Comment by onobc** [comment] 2023-08-29 04:07
@austek because this behavior is configurable (stopOnError) and the fact that it will be addressed in `1.0.0` as it uses Pulsar `3.x` which includes the serializers - we are going to close this as won't fix for `0.2.x`.

**Closed by onobc** 2023-08-29 04:07 UTC

**Comment by asoltesz** [comment] 2023-10-20 17:33
I have the same issue using 0.2 but with the non-reactive variant.

I would like to use 1.0.0 but it seems that it has not yet been released and I didn't manage to fix get the dependencies even from the milestone repo.

**Comment by onobc** [comment] 2023-10-20 18:04
Hi @asoltesz ,
If you go to start.spring.io you can select Spring Boot `3.2.0-RC1` and then add Spring Pulsar as a dependency and it will generate the configuration for the repos for you. 

https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.2.0-RC1&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=pulsar

Adjust from Maven to Gradle depending on what build system you are using.
